twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        global_variables: '@App\Service\GlobalVariables'

when@test:
    twig:
        strict_variables: true
